target-version = "py312"
line-length = 80

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "UP",  # pyupgrade
    "TID", # flake8-tidy-imports
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "NPY", # numpy rules (if used)
]
ignore = []

[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false

[isort]
known-first-party = ["openmip"]
combine-as-imports = true
